package erpsolims.erpsolimsmodel.erpsolimseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 09 20:12:46 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InDocumentShipmentHeaderImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ShipmentHeaderSno,
        ShipmentHeaderId,
        Locationid,
        ShipmentDate,
        DepartureFrom,
        VehicleNo,
        DriverName,
        DriverContactNo,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        Posted,
        Storeid,
        txtStoreName,
        Remarks,
        InDocumentShipmentLines,
        AllStores;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHIPMENTHEADERSNO = AttributesEnum.ShipmentHeaderSno.index();
    public static final int SHIPMENTHEADERID = AttributesEnum.ShipmentHeaderId.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int DEPARTUREFROM = AttributesEnum.DepartureFrom.index();
    public static final int VEHICLENO = AttributesEnum.VehicleNo.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVERCONTACTNO = AttributesEnum.DriverContactNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int INDOCUMENTSHIPMENTLINES = AttributesEnum.InDocumentShipmentLines.index();
    public static final int ALLSTORES = AttributesEnum.AllStores.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InDocumentShipmentHeaderImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolims.erpsolimsmodel.erpsolimseo.InDocumentShipmentHeader");
    }


    /**
     * Gets the attribute value for ShipmentHeaderSno, using the alias name ShipmentHeaderSno.
     * @return the value of ShipmentHeaderSno
     */
    public Integer getShipmentHeaderSno() {
        return (Integer) getAttributeInternal(SHIPMENTHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentHeaderSno.
     * @param value value to set the ShipmentHeaderSno
     */
    public void setShipmentHeaderSno(Integer value) {
        setAttributeInternal(SHIPMENTHEADERSNO, value);
    }

    /**
     * Gets the attribute value for ShipmentHeaderId, using the alias name ShipmentHeaderId.
     * @return the value of ShipmentHeaderId
     */
    public String getShipmentHeaderId() {
        return (String) getAttributeInternal(SHIPMENTHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentHeaderId.
     * @param value value to set the ShipmentHeaderId
     */
    public void setShipmentHeaderId(String value) {
        setAttributeInternal(SHIPMENTHEADERID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for ShipmentDate, using the alias name ShipmentDate.
     * @return the value of ShipmentDate
     */
    public Date getShipmentDate() {
        return (Date) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentDate.
     * @param value value to set the ShipmentDate
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for DepartureFrom, using the alias name DepartureFrom.
     * @return the value of DepartureFrom
     */
    public String getDepartureFrom() {
        return (String) getAttributeInternal(DEPARTUREFROM);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartureFrom.
     * @param value value to set the DepartureFrom
     */
    public void setDepartureFrom(String value) {
        setAttributeInternal(DEPARTUREFROM, value);
    }

    /**
     * Gets the attribute value for VehicleNo, using the alias name VehicleNo.
     * @return the value of VehicleNo
     */
    public String getVehicleNo() {
        return (String) getAttributeInternal(VEHICLENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for VehicleNo.
     * @param value value to set the VehicleNo
     */
    public void setVehicleNo(String value) {
        setAttributeInternal(VEHICLENO, value);
    }

    /**
     * Gets the attribute value for DriverName, using the alias name DriverName.
     * @return the value of DriverName
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverName.
     * @param value value to set the DriverName
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for DriverContactNo, using the alias name DriverContactNo.
     * @return the value of DriverContactNo
     */
    public String getDriverContactNo() {
        return (String) getAttributeInternal(DRIVERCONTACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DriverContactNo.
     * @param value value to set the DriverContactNo
     */
    public void setDriverContactNo(String value) {
        setAttributeInternal(DRIVERCONTACTNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Storeid, using the alias name Storeid.
     * @return the value of Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Storeid.
     * @param value value to set the Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for txtStoreName, using the alias name txtStoreName.
     * @return the value of txtStoreName
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtStoreName.
     * @param value value to set the txtStoreName
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInDocumentShipmentLines() {
        return (RowIterator) getAttributeInternal(INDOCUMENTSHIPMENTLINES);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllStores() {
        return (EntityImpl) getAttributeInternal(ALLSTORES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllStores(EntityImpl value) {
        setAttributeInternal(ALLSTORES, value);
    }


    /**
     * @param shipmentHeaderSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer shipmentHeaderSno) {
        return new Key(new Object[] { shipmentHeaderSno });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }
@Override
    protected void create(AttributeList attributeList) {
        // TODO Implement this method
        
        setERPSolPKColumnName("ShipmentHeaderSno");
        setERPSolPKSeqName("IN_DOCUMENT_SHIPMENT_HEADER_SQ");
        setLocationid(ERPSolGlobClassModel.doGetUserLocationCode());
        setStoreid(ERPSolGlobClassModel.doGetUserStoreCode());
        super.create(attributeList);
    }
    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String pkValue=" func_get_document_id('IN_DOCUMENT_SHIPMENT_HEADER','SHIPMENT_HEADER_ID','"+getLocationid()+"',TO_DATE('"+getShipmentDate()+"','YYYY-MM-DD'))";
           System.out.println(pkValue + "IN_DOCUMENT_SHIPMENT_HEADER pk value");
           String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
           populateAttributeAsChanged(SHIPMENTHEADERID, result);

        }
        super.doDML(operation, e);
    }
    
}

