package erpsolims.erpsolimsmodel.erpsolimseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 09 20:16:54 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InDocumentShipmentLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ShipmentLinesSno,
        ShipmentHeaderSno,
        DocumentId,
        DocumentType,
        Quantity,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        InDocumentShipmentHeader;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SHIPMENTLINESSNO = AttributesEnum.ShipmentLinesSno.index();
    public static final int SHIPMENTHEADERSNO = AttributesEnum.ShipmentHeaderSno.index();
    public static final int DOCUMENTID = AttributesEnum.DocumentId.index();
    public static final int DOCUMENTTYPE = AttributesEnum.DocumentType.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int INDOCUMENTSHIPMENTHEADER = AttributesEnum.InDocumentShipmentHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InDocumentShipmentLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolims.erpsolimsmodel.erpsolimseo.InDocumentShipmentLines");
    }

    /**
     * Gets the attribute value for ShipmentLinesSno, using the alias name ShipmentLinesSno.
     * @return the value of ShipmentLinesSno
     */
    public Integer getShipmentLinesSno() {
        return (Integer) getAttributeInternal(SHIPMENTLINESSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentLinesSno.
     * @param value value to set the ShipmentLinesSno
     */
    public void setShipmentLinesSno(Integer value) {
        setAttributeInternal(SHIPMENTLINESSNO, value);
    }

    /**
     * Gets the attribute value for ShipmentHeaderSno, using the alias name ShipmentHeaderSno.
     * @return the value of ShipmentHeaderSno
     */
    public Integer getShipmentHeaderSno() {
        return (Integer) getAttributeInternal(SHIPMENTHEADERSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentHeaderSno.
     * @param value value to set the ShipmentHeaderSno
     */
    public void setShipmentHeaderSno(Integer value) {
        setAttributeInternal(SHIPMENTHEADERSNO, value);
    }

    /**
     * Gets the attribute value for DocumentId, using the alias name DocumentId.
     * @return the value of DocumentId
     */
    public String getDocumentId() {
        return (String) getAttributeInternal(DOCUMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentId.
     * @param value value to set the DocumentId
     */
    public void setDocumentId(String value) {
        setAttributeInternal(DOCUMENTID, value);
    }

    /**
     * Gets the attribute value for DocumentType, using the alias name DocumentType.
     * @return the value of DocumentType
     */
    public String getDocumentType() {
        return (String) getAttributeInternal(DOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentType.
     * @param value value to set the DocumentType
     */
    public void setDocumentType(String value) {
        setAttributeInternal(DOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the value of ModifiedBy
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedBy.
     * @param value value to set the ModifiedBy
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * @return the associated entity InDocumentShipmentHeaderImpl.
     */
    public InDocumentShipmentHeaderImpl getInDocumentShipmentHeader() {
        return (InDocumentShipmentHeaderImpl) getAttributeInternal(INDOCUMENTSHIPMENTHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity InDocumentShipmentHeaderImpl.
     */
    public void setInDocumentShipmentHeader(InDocumentShipmentHeaderImpl value) {
        setAttributeInternal(INDOCUMENTSHIPMENTHEADER, value);
    }


    /**
     * @param shipmentLinesSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer shipmentLinesSno) {
        return new Key(new Object[] { shipmentLinesSno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("ShipmentLinesSno");
        setERPSolPKSeqName("IN_DOCUMENT_SHIPMENT_LINES_SEQ");
        super.create(attributeList);
    }
}

