package erpsolims.erpsolimsmodel.erpsolimseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Mar 26 12:30:34 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InItemsImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Itemid,
        ItemRefId,
        Uomsid,
        Productid,
        Sigroupid,
        Siclassid,
        Description,
        ModelNo,
        Createdby,
        CreatedDate,
        Modifiedby,
        LeadTime,
        ModifiedDate,
        Pglcode,
        Pccenter,
        Iglcode,
        Iccenter,
        Sglcode,
        Sccenter,
        Mglcode,
        Mccenter,
        Cglcode,
        Cccenter,
        Productsubtype,
        Scglcode,
        Scccenter,
        Uglcode,
        Uccenter,
        ReceUomsid,
        Plglcode,
        Plccenter,
        Srglcode,
        Srccenter,
        Specification,
        SerialFlag,
        PpaNo,
        Hscode,
        Currcode,
        HsRate,
        Pplgroupid,
        AppKitExtraQty,
        ConvCost,
        ExpGlcode,
        ExpCcenter,
        AdjGlcode,
        AdjCcenter,
        Stax,
        Itax,
        Discontinue,
        OldItemid,
        ObsoleteItem,
        Rate,
        Itgroupid,
        Smgroupid,
        SmRates,
        SmMinSellingPrice,
        StRates,
        StDis,
        Sed,
        ExtraTax,
        ItemStatus,
        Rd,
        Divid,
        ExtraSno,
        Childpartno,
        Partweight,
        Partno,
        TacCode,
        ProdId,
        Brandid,
        Subgroupid,
        ItemWeight,
        EolDesc,
        Print,
        Perbox,
        TypeApproval,
        TmpItemid,
        TmpItemDesc,
        Newmodle,
        Desce,
        Incentive,
        IncMsg,
        SaleDays,
        RetQtyExempted,
        ItemRebateAct,
        RestrictBoxNo,
        IsSpecial,
        IsRunning,
        CounterDeadDays,
        RestrictRebateSo,
        StopCustomer,
        ExcludeGiftQty,
        ImeiSerial,
        ForceAllowReturn,
        IsPreviousSameRate,
        PreviousRebateRate,
        WrefreshDate,
        IsStopWrefReturn,
        RebateDays,
        IncPst,
        EbsItemid,
        IsReturnAllow,
        Active,
        IsImeiWiseRetAllow,
        ProdItemid,
        ScreenSize,
        ActualFlatRate,
        IntraCompanyItemid,
        IntraCompanyProductid,
        LandedCost,
        BarCode,
        Siclassidn,
        Sigroupidn,
        Itgroupidn,
        Discount,
        ItemCost,
        WcpShortName,
        InReceivedItemsLines,
        InItemTransferNoteLines,
        SoProducts,
        InStoreItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMREFID = AttributesEnum.ItemRefId.index();
    public static final int UOMSID = AttributesEnum.Uomsid.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int SIGROUPID = AttributesEnum.Sigroupid.index();
    public static final int SICLASSID = AttributesEnum.Siclassid.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int MODELNO = AttributesEnum.ModelNo.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int LEADTIME = AttributesEnum.LeadTime.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int PGLCODE = AttributesEnum.Pglcode.index();
    public static final int PCCENTER = AttributesEnum.Pccenter.index();
    public static final int IGLCODE = AttributesEnum.Iglcode.index();
    public static final int ICCENTER = AttributesEnum.Iccenter.index();
    public static final int SGLCODE = AttributesEnum.Sglcode.index();
    public static final int SCCENTER = AttributesEnum.Sccenter.index();
    public static final int MGLCODE = AttributesEnum.Mglcode.index();
    public static final int MCCENTER = AttributesEnum.Mccenter.index();
    public static final int CGLCODE = AttributesEnum.Cglcode.index();
    public static final int CCCENTER = AttributesEnum.Cccenter.index();
    public static final int PRODUCTSUBTYPE = AttributesEnum.Productsubtype.index();
    public static final int SCGLCODE = AttributesEnum.Scglcode.index();
    public static final int SCCCENTER = AttributesEnum.Scccenter.index();
    public static final int UGLCODE = AttributesEnum.Uglcode.index();
    public static final int UCCENTER = AttributesEnum.Uccenter.index();
    public static final int RECEUOMSID = AttributesEnum.ReceUomsid.index();
    public static final int PLGLCODE = AttributesEnum.Plglcode.index();
    public static final int PLCCENTER = AttributesEnum.Plccenter.index();
    public static final int SRGLCODE = AttributesEnum.Srglcode.index();
    public static final int SRCCENTER = AttributesEnum.Srccenter.index();
    public static final int SPECIFICATION = AttributesEnum.Specification.index();
    public static final int SERIALFLAG = AttributesEnum.SerialFlag.index();
    public static final int PPANO = AttributesEnum.PpaNo.index();
    public static final int HSCODE = AttributesEnum.Hscode.index();
    public static final int CURRCODE = AttributesEnum.Currcode.index();
    public static final int HSRATE = AttributesEnum.HsRate.index();
    public static final int PPLGROUPID = AttributesEnum.Pplgroupid.index();
    public static final int APPKITEXTRAQTY = AttributesEnum.AppKitExtraQty.index();
    public static final int CONVCOST = AttributesEnum.ConvCost.index();
    public static final int EXPGLCODE = AttributesEnum.ExpGlcode.index();
    public static final int EXPCCENTER = AttributesEnum.ExpCcenter.index();
    public static final int ADJGLCODE = AttributesEnum.AdjGlcode.index();
    public static final int ADJCCENTER = AttributesEnum.AdjCcenter.index();
    public static final int STAX = AttributesEnum.Stax.index();
    public static final int ITAX = AttributesEnum.Itax.index();
    public static final int DISCONTINUE = AttributesEnum.Discontinue.index();
    public static final int OLDITEMID = AttributesEnum.OldItemid.index();
    public static final int OBSOLETEITEM = AttributesEnum.ObsoleteItem.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int ITGROUPID = AttributesEnum.Itgroupid.index();
    public static final int SMGROUPID = AttributesEnum.Smgroupid.index();
    public static final int SMRATES = AttributesEnum.SmRates.index();
    public static final int SMMINSELLINGPRICE = AttributesEnum.SmMinSellingPrice.index();
    public static final int STRATES = AttributesEnum.StRates.index();
    public static final int STDIS = AttributesEnum.StDis.index();
    public static final int SED = AttributesEnum.Sed.index();
    public static final int EXTRATAX = AttributesEnum.ExtraTax.index();
    public static final int ITEMSTATUS = AttributesEnum.ItemStatus.index();
    public static final int RD = AttributesEnum.Rd.index();
    public static final int DIVID = AttributesEnum.Divid.index();
    public static final int EXTRASNO = AttributesEnum.ExtraSno.index();
    public static final int CHILDPARTNO = AttributesEnum.Childpartno.index();
    public static final int PARTWEIGHT = AttributesEnum.Partweight.index();
    public static final int PARTNO = AttributesEnum.Partno.index();
    public static final int TACCODE = AttributesEnum.TacCode.index();
    public static final int PRODID = AttributesEnum.ProdId.index();
    public static final int BRANDID = AttributesEnum.Brandid.index();
    public static final int SUBGROUPID = AttributesEnum.Subgroupid.index();
    public static final int ITEMWEIGHT = AttributesEnum.ItemWeight.index();
    public static final int EOLDESC = AttributesEnum.EolDesc.index();
    public static final int PRINT = AttributesEnum.Print.index();
    public static final int PERBOX = AttributesEnum.Perbox.index();
    public static final int TYPEAPPROVAL = AttributesEnum.TypeApproval.index();
    public static final int TMPITEMID = AttributesEnum.TmpItemid.index();
    public static final int TMPITEMDESC = AttributesEnum.TmpItemDesc.index();
    public static final int NEWMODLE = AttributesEnum.Newmodle.index();
    public static final int DESCE = AttributesEnum.Desce.index();
    public static final int INCENTIVE = AttributesEnum.Incentive.index();
    public static final int INCMSG = AttributesEnum.IncMsg.index();
    public static final int SALEDAYS = AttributesEnum.SaleDays.index();
    public static final int RETQTYEXEMPTED = AttributesEnum.RetQtyExempted.index();
    public static final int ITEMREBATEACT = AttributesEnum.ItemRebateAct.index();
    public static final int RESTRICTBOXNO = AttributesEnum.RestrictBoxNo.index();
    public static final int ISSPECIAL = AttributesEnum.IsSpecial.index();
    public static final int ISRUNNING = AttributesEnum.IsRunning.index();
    public static final int COUNTERDEADDAYS = AttributesEnum.CounterDeadDays.index();
    public static final int RESTRICTREBATESO = AttributesEnum.RestrictRebateSo.index();
    public static final int STOPCUSTOMER = AttributesEnum.StopCustomer.index();
    public static final int EXCLUDEGIFTQTY = AttributesEnum.ExcludeGiftQty.index();
    public static final int IMEISERIAL = AttributesEnum.ImeiSerial.index();
    public static final int FORCEALLOWRETURN = AttributesEnum.ForceAllowReturn.index();
    public static final int ISPREVIOUSSAMERATE = AttributesEnum.IsPreviousSameRate.index();
    public static final int PREVIOUSREBATERATE = AttributesEnum.PreviousRebateRate.index();
    public static final int WREFRESHDATE = AttributesEnum.WrefreshDate.index();
    public static final int ISSTOPWREFRETURN = AttributesEnum.IsStopWrefReturn.index();
    public static final int REBATEDAYS = AttributesEnum.RebateDays.index();
    public static final int INCPST = AttributesEnum.IncPst.index();
    public static final int EBSITEMID = AttributesEnum.EbsItemid.index();
    public static final int ISRETURNALLOW = AttributesEnum.IsReturnAllow.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int ISIMEIWISERETALLOW = AttributesEnum.IsImeiWiseRetAllow.index();
    public static final int PRODITEMID = AttributesEnum.ProdItemid.index();
    public static final int SCREENSIZE = AttributesEnum.ScreenSize.index();
    public static final int ACTUALFLATRATE = AttributesEnum.ActualFlatRate.index();
    public static final int INTRACOMPANYITEMID = AttributesEnum.IntraCompanyItemid.index();
    public static final int INTRACOMPANYPRODUCTID = AttributesEnum.IntraCompanyProductid.index();
    public static final int LANDEDCOST = AttributesEnum.LandedCost.index();
    public static final int BARCODE = AttributesEnum.BarCode.index();
    public static final int SICLASSIDN = AttributesEnum.Siclassidn.index();
    public static final int SIGROUPIDN = AttributesEnum.Sigroupidn.index();
    public static final int ITGROUPIDN = AttributesEnum.Itgroupidn.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int ITEMCOST = AttributesEnum.ItemCost.index();
    public static final int WCPSHORTNAME = AttributesEnum.WcpShortName.index();
    public static final int INRECEIVEDITEMSLINES = AttributesEnum.InReceivedItemsLines.index();
    public static final int INITEMTRANSFERNOTELINES = AttributesEnum.InItemTransferNoteLines.index();
    public static final int SOPRODUCTS = AttributesEnum.SoProducts.index();
    public static final int INSTOREITEMS = AttributesEnum.InStoreItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InItemsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolims.erpsolimsmodel.erpsolimseo.InItems");
    }


    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemRefId, using the alias name ItemRefId.
     * @return the value of ItemRefId
     */
    public String getItemRefId() {
        return (String) getAttributeInternal(ITEMREFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemRefId.
     * @param value value to set the ItemRefId
     */
    public void setItemRefId(String value) {
        setAttributeInternal(ITEMREFID, value);
    }

    /**
     * Gets the attribute value for Uomsid, using the alias name Uomsid.
     * @return the value of Uomsid
     */
    public String getUomsid() {
        return (String) getAttributeInternal(UOMSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uomsid.
     * @param value value to set the Uomsid
     */
    public void setUomsid(String value) {
        setAttributeInternal(UOMSID, value);
    }

    /**
     * Gets the attribute value for Productid, using the alias name Productid.
     * @return the value of Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productid.
     * @param value value to set the Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for Sigroupid, using the alias name Sigroupid.
     * @return the value of Sigroupid
     */
    public String getSigroupid() {
        return (String) getAttributeInternal(SIGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sigroupid.
     * @param value value to set the Sigroupid
     */
    public void setSigroupid(String value) {
        setAttributeInternal(SIGROUPID, value);
    }

    /**
     * Gets the attribute value for Siclassid, using the alias name Siclassid.
     * @return the value of Siclassid
     */
    public String getSiclassid() {
        return (String) getAttributeInternal(SICLASSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Siclassid.
     * @param value value to set the Siclassid
     */
    public void setSiclassid(String value) {
        setAttributeInternal(SICLASSID, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ModelNo, using the alias name ModelNo.
     * @return the value of ModelNo
     */
    public String getModelNo() {
        return (String) getAttributeInternal(MODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModelNo.
     * @param value value to set the ModelNo
     */
    public void setModelNo(String value) {
        setAttributeInternal(MODELNO, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for LeadTime, using the alias name LeadTime.
     * @return the value of LeadTime
     */
    public BigDecimal getLeadTime() {
        return (BigDecimal) getAttributeInternal(LEADTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LeadTime.
     * @param value value to set the LeadTime
     */
    public void setLeadTime(BigDecimal value) {
        setAttributeInternal(LEADTIME, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Pglcode, using the alias name Pglcode.
     * @return the value of Pglcode
     */
    public String getPglcode() {
        return (String) getAttributeInternal(PGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pglcode.
     * @param value value to set the Pglcode
     */
    public void setPglcode(String value) {
        setAttributeInternal(PGLCODE, value);
    }

    /**
     * Gets the attribute value for Pccenter, using the alias name Pccenter.
     * @return the value of Pccenter
     */
    public String getPccenter() {
        return (String) getAttributeInternal(PCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pccenter.
     * @param value value to set the Pccenter
     */
    public void setPccenter(String value) {
        setAttributeInternal(PCCENTER, value);
    }

    /**
     * Gets the attribute value for Iglcode, using the alias name Iglcode.
     * @return the value of Iglcode
     */
    public String getIglcode() {
        return (String) getAttributeInternal(IGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Iglcode.
     * @param value value to set the Iglcode
     */
    public void setIglcode(String value) {
        setAttributeInternal(IGLCODE, value);
    }

    /**
     * Gets the attribute value for Iccenter, using the alias name Iccenter.
     * @return the value of Iccenter
     */
    public String getIccenter() {
        return (String) getAttributeInternal(ICCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Iccenter.
     * @param value value to set the Iccenter
     */
    public void setIccenter(String value) {
        setAttributeInternal(ICCENTER, value);
    }

    /**
     * Gets the attribute value for Sglcode, using the alias name Sglcode.
     * @return the value of Sglcode
     */
    public String getSglcode() {
        return (String) getAttributeInternal(SGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sglcode.
     * @param value value to set the Sglcode
     */
    public void setSglcode(String value) {
        setAttributeInternal(SGLCODE, value);
    }

    /**
     * Gets the attribute value for Sccenter, using the alias name Sccenter.
     * @return the value of Sccenter
     */
    public String getSccenter() {
        return (String) getAttributeInternal(SCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sccenter.
     * @param value value to set the Sccenter
     */
    public void setSccenter(String value) {
        setAttributeInternal(SCCENTER, value);
    }

    /**
     * Gets the attribute value for Mglcode, using the alias name Mglcode.
     * @return the value of Mglcode
     */
    public String getMglcode() {
        return (String) getAttributeInternal(MGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mglcode.
     * @param value value to set the Mglcode
     */
    public void setMglcode(String value) {
        setAttributeInternal(MGLCODE, value);
    }

    /**
     * Gets the attribute value for Mccenter, using the alias name Mccenter.
     * @return the value of Mccenter
     */
    public String getMccenter() {
        return (String) getAttributeInternal(MCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mccenter.
     * @param value value to set the Mccenter
     */
    public void setMccenter(String value) {
        setAttributeInternal(MCCENTER, value);
    }

    /**
     * Gets the attribute value for Cglcode, using the alias name Cglcode.
     * @return the value of Cglcode
     */
    public String getCglcode() {
        return (String) getAttributeInternal(CGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cglcode.
     * @param value value to set the Cglcode
     */
    public void setCglcode(String value) {
        setAttributeInternal(CGLCODE, value);
    }

    /**
     * Gets the attribute value for Cccenter, using the alias name Cccenter.
     * @return the value of Cccenter
     */
    public String getCccenter() {
        return (String) getAttributeInternal(CCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cccenter.
     * @param value value to set the Cccenter
     */
    public void setCccenter(String value) {
        setAttributeInternal(CCCENTER, value);
    }

    /**
     * Gets the attribute value for Productsubtype, using the alias name Productsubtype.
     * @return the value of Productsubtype
     */
    public String getProductsubtype() {
        return (String) getAttributeInternal(PRODUCTSUBTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productsubtype.
     * @param value value to set the Productsubtype
     */
    public void setProductsubtype(String value) {
        setAttributeInternal(PRODUCTSUBTYPE, value);
    }

    /**
     * Gets the attribute value for Scglcode, using the alias name Scglcode.
     * @return the value of Scglcode
     */
    public String getScglcode() {
        return (String) getAttributeInternal(SCGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scglcode.
     * @param value value to set the Scglcode
     */
    public void setScglcode(String value) {
        setAttributeInternal(SCGLCODE, value);
    }

    /**
     * Gets the attribute value for Scccenter, using the alias name Scccenter.
     * @return the value of Scccenter
     */
    public String getScccenter() {
        return (String) getAttributeInternal(SCCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Scccenter.
     * @param value value to set the Scccenter
     */
    public void setScccenter(String value) {
        setAttributeInternal(SCCCENTER, value);
    }

    /**
     * Gets the attribute value for Uglcode, using the alias name Uglcode.
     * @return the value of Uglcode
     */
    public String getUglcode() {
        return (String) getAttributeInternal(UGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uglcode.
     * @param value value to set the Uglcode
     */
    public void setUglcode(String value) {
        setAttributeInternal(UGLCODE, value);
    }

    /**
     * Gets the attribute value for Uccenter, using the alias name Uccenter.
     * @return the value of Uccenter
     */
    public String getUccenter() {
        return (String) getAttributeInternal(UCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uccenter.
     * @param value value to set the Uccenter
     */
    public void setUccenter(String value) {
        setAttributeInternal(UCCENTER, value);
    }

    /**
     * Gets the attribute value for ReceUomsid, using the alias name ReceUomsid.
     * @return the value of ReceUomsid
     */
    public String getReceUomsid() {
        return (String) getAttributeInternal(RECEUOMSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceUomsid.
     * @param value value to set the ReceUomsid
     */
    public void setReceUomsid(String value) {
        setAttributeInternal(RECEUOMSID, value);
    }

    /**
     * Gets the attribute value for Plglcode, using the alias name Plglcode.
     * @return the value of Plglcode
     */
    public String getPlglcode() {
        return (String) getAttributeInternal(PLGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plglcode.
     * @param value value to set the Plglcode
     */
    public void setPlglcode(String value) {
        setAttributeInternal(PLGLCODE, value);
    }

    /**
     * Gets the attribute value for Plccenter, using the alias name Plccenter.
     * @return the value of Plccenter
     */
    public String getPlccenter() {
        return (String) getAttributeInternal(PLCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Plccenter.
     * @param value value to set the Plccenter
     */
    public void setPlccenter(String value) {
        setAttributeInternal(PLCCENTER, value);
    }

    /**
     * Gets the attribute value for Srglcode, using the alias name Srglcode.
     * @return the value of Srglcode
     */
    public String getSrglcode() {
        return (String) getAttributeInternal(SRGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Srglcode.
     * @param value value to set the Srglcode
     */
    public void setSrglcode(String value) {
        setAttributeInternal(SRGLCODE, value);
    }

    /**
     * Gets the attribute value for Srccenter, using the alias name Srccenter.
     * @return the value of Srccenter
     */
    public String getSrccenter() {
        return (String) getAttributeInternal(SRCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Srccenter.
     * @param value value to set the Srccenter
     */
    public void setSrccenter(String value) {
        setAttributeInternal(SRCCENTER, value);
    }

    /**
     * Gets the attribute value for Specification, using the alias name Specification.
     * @return the value of Specification
     */
    public String getSpecification() {
        return (String) getAttributeInternal(SPECIFICATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Specification.
     * @param value value to set the Specification
     */
    public void setSpecification(String value) {
        setAttributeInternal(SPECIFICATION, value);
    }

    /**
     * Gets the attribute value for SerialFlag, using the alias name SerialFlag.
     * @return the value of SerialFlag
     */
    public String getSerialFlag() {
        return (String) getAttributeInternal(SERIALFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SerialFlag.
     * @param value value to set the SerialFlag
     */
    public void setSerialFlag(String value) {
        setAttributeInternal(SERIALFLAG, value);
    }

    /**
     * Gets the attribute value for PpaNo, using the alias name PpaNo.
     * @return the value of PpaNo
     */
    public String getPpaNo() {
        return (String) getAttributeInternal(PPANO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PpaNo.
     * @param value value to set the PpaNo
     */
    public void setPpaNo(String value) {
        setAttributeInternal(PPANO, value);
    }

    /**
     * Gets the attribute value for Hscode, using the alias name Hscode.
     * @return the value of Hscode
     */
    public String getHscode() {
        return (String) getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hscode.
     * @param value value to set the Hscode
     */
    public void setHscode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for Currcode, using the alias name Currcode.
     * @return the value of Currcode
     */
    public String getCurrcode() {
        return (String) getAttributeInternal(CURRCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currcode.
     * @param value value to set the Currcode
     */
    public void setCurrcode(String value) {
        setAttributeInternal(CURRCODE, value);
    }

    /**
     * Gets the attribute value for HsRate, using the alias name HsRate.
     * @return the value of HsRate
     */
    public BigDecimal getHsRate() {
        return (BigDecimal) getAttributeInternal(HSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HsRate.
     * @param value value to set the HsRate
     */
    public void setHsRate(BigDecimal value) {
        setAttributeInternal(HSRATE, value);
    }

    /**
     * Gets the attribute value for Pplgroupid, using the alias name Pplgroupid.
     * @return the value of Pplgroupid
     */
    public String getPplgroupid() {
        return (String) getAttributeInternal(PPLGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Pplgroupid.
     * @param value value to set the Pplgroupid
     */
    public void setPplgroupid(String value) {
        setAttributeInternal(PPLGROUPID, value);
    }

    /**
     * Gets the attribute value for AppKitExtraQty, using the alias name AppKitExtraQty.
     * @return the value of AppKitExtraQty
     */
    public String getAppKitExtraQty() {
        return (String) getAttributeInternal(APPKITEXTRAQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for AppKitExtraQty.
     * @param value value to set the AppKitExtraQty
     */
    public void setAppKitExtraQty(String value) {
        setAttributeInternal(APPKITEXTRAQTY, value);
    }

    /**
     * Gets the attribute value for ConvCost, using the alias name ConvCost.
     * @return the value of ConvCost
     */
    public BigDecimal getConvCost() {
        return (BigDecimal) getAttributeInternal(CONVCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConvCost.
     * @param value value to set the ConvCost
     */
    public void setConvCost(BigDecimal value) {
        setAttributeInternal(CONVCOST, value);
    }

    /**
     * Gets the attribute value for ExpGlcode, using the alias name ExpGlcode.
     * @return the value of ExpGlcode
     */
    public String getExpGlcode() {
        return (String) getAttributeInternal(EXPGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpGlcode.
     * @param value value to set the ExpGlcode
     */
    public void setExpGlcode(String value) {
        setAttributeInternal(EXPGLCODE, value);
    }

    /**
     * Gets the attribute value for ExpCcenter, using the alias name ExpCcenter.
     * @return the value of ExpCcenter
     */
    public String getExpCcenter() {
        return (String) getAttributeInternal(EXPCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpCcenter.
     * @param value value to set the ExpCcenter
     */
    public void setExpCcenter(String value) {
        setAttributeInternal(EXPCCENTER, value);
    }

    /**
     * Gets the attribute value for AdjGlcode, using the alias name AdjGlcode.
     * @return the value of AdjGlcode
     */
    public String getAdjGlcode() {
        return (String) getAttributeInternal(ADJGLCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdjGlcode.
     * @param value value to set the AdjGlcode
     */
    public void setAdjGlcode(String value) {
        setAttributeInternal(ADJGLCODE, value);
    }

    /**
     * Gets the attribute value for AdjCcenter, using the alias name AdjCcenter.
     * @return the value of AdjCcenter
     */
    public String getAdjCcenter() {
        return (String) getAttributeInternal(ADJCCENTER);
    }

    /**
     * Sets <code>value</code> as the attribute value for AdjCcenter.
     * @param value value to set the AdjCcenter
     */
    public void setAdjCcenter(String value) {
        setAttributeInternal(ADJCCENTER, value);
    }

    /**
     * Gets the attribute value for Stax, using the alias name Stax.
     * @return the value of Stax
     */
    public String getStax() {
        return (String) getAttributeInternal(STAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stax.
     * @param value value to set the Stax
     */
    public void setStax(String value) {
        setAttributeInternal(STAX, value);
    }

    /**
     * Gets the attribute value for Itax, using the alias name Itax.
     * @return the value of Itax
     */
    public String getItax() {
        return (String) getAttributeInternal(ITAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itax.
     * @param value value to set the Itax
     */
    public void setItax(String value) {
        setAttributeInternal(ITAX, value);
    }

    /**
     * Gets the attribute value for Discontinue, using the alias name Discontinue.
     * @return the value of Discontinue
     */
    public String getDiscontinue() {
        return (String) getAttributeInternal(DISCONTINUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discontinue.
     * @param value value to set the Discontinue
     */
    public void setDiscontinue(String value) {
        setAttributeInternal(DISCONTINUE, value);
    }

    /**
     * Gets the attribute value for OldItemid, using the alias name OldItemid.
     * @return the value of OldItemid
     */
    public String getOldItemid() {
        return (String) getAttributeInternal(OLDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OldItemid.
     * @param value value to set the OldItemid
     */
    public void setOldItemid(String value) {
        setAttributeInternal(OLDITEMID, value);
    }

    /**
     * Gets the attribute value for ObsoleteItem, using the alias name ObsoleteItem.
     * @return the value of ObsoleteItem
     */
    public String getObsoleteItem() {
        return (String) getAttributeInternal(OBSOLETEITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ObsoleteItem.
     * @param value value to set the ObsoleteItem
     */
    public void setObsoleteItem(String value) {
        setAttributeInternal(OBSOLETEITEM, value);
    }

    /**
     * Gets the attribute value for Rate, using the alias name Rate.
     * @return the value of Rate
     */
    public BigDecimal getRate() {
        return (BigDecimal) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rate.
     * @param value value to set the Rate
     */
    public void setRate(BigDecimal value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for Itgroupid, using the alias name Itgroupid.
     * @return the value of Itgroupid
     */
    public String getItgroupid() {
        return (String) getAttributeInternal(ITGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itgroupid.
     * @param value value to set the Itgroupid
     */
    public void setItgroupid(String value) {
        setAttributeInternal(ITGROUPID, value);
    }

    /**
     * Gets the attribute value for Smgroupid, using the alias name Smgroupid.
     * @return the value of Smgroupid
     */
    public String getSmgroupid() {
        return (String) getAttributeInternal(SMGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Smgroupid.
     * @param value value to set the Smgroupid
     */
    public void setSmgroupid(String value) {
        setAttributeInternal(SMGROUPID, value);
    }

    /**
     * Gets the attribute value for SmRates, using the alias name SmRates.
     * @return the value of SmRates
     */
    public BigDecimal getSmRates() {
        return (BigDecimal) getAttributeInternal(SMRATES);
    }

    /**
     * Sets <code>value</code> as the attribute value for SmRates.
     * @param value value to set the SmRates
     */
    public void setSmRates(BigDecimal value) {
        setAttributeInternal(SMRATES, value);
    }

    /**
     * Gets the attribute value for SmMinSellingPrice, using the alias name SmMinSellingPrice.
     * @return the value of SmMinSellingPrice
     */
    public BigDecimal getSmMinSellingPrice() {
        return (BigDecimal) getAttributeInternal(SMMINSELLINGPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SmMinSellingPrice.
     * @param value value to set the SmMinSellingPrice
     */
    public void setSmMinSellingPrice(BigDecimal value) {
        setAttributeInternal(SMMINSELLINGPRICE, value);
    }

    /**
     * Gets the attribute value for StRates, using the alias name StRates.
     * @return the value of StRates
     */
    public BigDecimal getStRates() {
        return (BigDecimal) getAttributeInternal(STRATES);
    }

    /**
     * Sets <code>value</code> as the attribute value for StRates.
     * @param value value to set the StRates
     */
    public void setStRates(BigDecimal value) {
        setAttributeInternal(STRATES, value);
    }

    /**
     * Gets the attribute value for StDis, using the alias name StDis.
     * @return the value of StDis
     */
    public BigDecimal getStDis() {
        return (BigDecimal) getAttributeInternal(STDIS);
    }

    /**
     * Sets <code>value</code> as the attribute value for StDis.
     * @param value value to set the StDis
     */
    public void setStDis(BigDecimal value) {
        setAttributeInternal(STDIS, value);
    }

    /**
     * Gets the attribute value for Sed, using the alias name Sed.
     * @return the value of Sed
     */
    public String getSed() {
        return (String) getAttributeInternal(SED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sed.
     * @param value value to set the Sed
     */
    public void setSed(String value) {
        setAttributeInternal(SED, value);
    }

    /**
     * Gets the attribute value for ExtraTax, using the alias name ExtraTax.
     * @return the value of ExtraTax
     */
    public String getExtraTax() {
        return (String) getAttributeInternal(EXTRATAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTax.
     * @param value value to set the ExtraTax
     */
    public void setExtraTax(String value) {
        setAttributeInternal(EXTRATAX, value);
    }

    /**
     * Gets the attribute value for ItemStatus, using the alias name ItemStatus.
     * @return the value of ItemStatus
     */
    public String getItemStatus() {
        return (String) getAttributeInternal(ITEMSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemStatus.
     * @param value value to set the ItemStatus
     */
    public void setItemStatus(String value) {
        setAttributeInternal(ITEMSTATUS, value);
    }

    /**
     * Gets the attribute value for Rd, using the alias name Rd.
     * @return the value of Rd
     */
    public String getRd() {
        return (String) getAttributeInternal(RD);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rd.
     * @param value value to set the Rd
     */
    public void setRd(String value) {
        setAttributeInternal(RD, value);
    }

    /**
     * Gets the attribute value for Divid, using the alias name Divid.
     * @return the value of Divid
     */
    public String getDivid() {
        return (String) getAttributeInternal(DIVID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Divid.
     * @param value value to set the Divid
     */
    public void setDivid(String value) {
        setAttributeInternal(DIVID, value);
    }

    /**
     * Gets the attribute value for ExtraSno, using the alias name ExtraSno.
     * @return the value of ExtraSno
     */
    public String getExtraSno() {
        return (String) getAttributeInternal(EXTRASNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraSno.
     * @param value value to set the ExtraSno
     */
    public void setExtraSno(String value) {
        setAttributeInternal(EXTRASNO, value);
    }

    /**
     * Gets the attribute value for Childpartno, using the alias name Childpartno.
     * @return the value of Childpartno
     */
    public String getChildpartno() {
        return (String) getAttributeInternal(CHILDPARTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Childpartno.
     * @param value value to set the Childpartno
     */
    public void setChildpartno(String value) {
        setAttributeInternal(CHILDPARTNO, value);
    }

    /**
     * Gets the attribute value for Partweight, using the alias name Partweight.
     * @return the value of Partweight
     */
    public BigDecimal getPartweight() {
        return (BigDecimal) getAttributeInternal(PARTWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Partweight.
     * @param value value to set the Partweight
     */
    public void setPartweight(BigDecimal value) {
        setAttributeInternal(PARTWEIGHT, value);
    }

    /**
     * Gets the attribute value for Partno, using the alias name Partno.
     * @return the value of Partno
     */
    public String getPartno() {
        return (String) getAttributeInternal(PARTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Partno.
     * @param value value to set the Partno
     */
    public void setPartno(String value) {
        setAttributeInternal(PARTNO, value);
    }

    /**
     * Gets the attribute value for TacCode, using the alias name TacCode.
     * @return the value of TacCode
     */
    public String getTacCode() {
        return (String) getAttributeInternal(TACCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TacCode.
     * @param value value to set the TacCode
     */
    public void setTacCode(String value) {
        setAttributeInternal(TACCODE, value);
    }

    /**
     * Gets the attribute value for ProdId, using the alias name ProdId.
     * @return the value of ProdId
     */
    public String getProdId() {
        return (String) getAttributeInternal(PRODID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdId.
     * @param value value to set the ProdId
     */
    public void setProdId(String value) {
        setAttributeInternal(PRODID, value);
    }

    /**
     * Gets the attribute value for Brandid, using the alias name Brandid.
     * @return the value of Brandid
     */
    public String getBrandid() {
        return (String) getAttributeInternal(BRANDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brandid.
     * @param value value to set the Brandid
     */
    public void setBrandid(String value) {
        setAttributeInternal(BRANDID, value);
    }

    /**
     * Gets the attribute value for Subgroupid, using the alias name Subgroupid.
     * @return the value of Subgroupid
     */
    public String getSubgroupid() {
        return (String) getAttributeInternal(SUBGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Subgroupid.
     * @param value value to set the Subgroupid
     */
    public void setSubgroupid(String value) {
        setAttributeInternal(SUBGROUPID, value);
    }

    /**
     * Gets the attribute value for ItemWeight, using the alias name ItemWeight.
     * @return the value of ItemWeight
     */
    public BigDecimal getItemWeight() {
        return (BigDecimal) getAttributeInternal(ITEMWEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemWeight.
     * @param value value to set the ItemWeight
     */
    public void setItemWeight(BigDecimal value) {
        setAttributeInternal(ITEMWEIGHT, value);
    }

    /**
     * Gets the attribute value for EolDesc, using the alias name EolDesc.
     * @return the value of EolDesc
     */
    public String getEolDesc() {
        return (String) getAttributeInternal(EOLDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for EolDesc.
     * @param value value to set the EolDesc
     */
    public void setEolDesc(String value) {
        setAttributeInternal(EOLDESC, value);
    }

    /**
     * Gets the attribute value for Print, using the alias name Print.
     * @return the value of Print
     */
    public Integer getPrint() {
        return (Integer) getAttributeInternal(PRINT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Print.
     * @param value value to set the Print
     */
    public void setPrint(Integer value) {
        setAttributeInternal(PRINT, value);
    }

    /**
     * Gets the attribute value for Perbox, using the alias name Perbox.
     * @return the value of Perbox
     */
    public Integer getPerbox() {
        return (Integer) getAttributeInternal(PERBOX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Perbox.
     * @param value value to set the Perbox
     */
    public void setPerbox(Integer value) {
        setAttributeInternal(PERBOX, value);
    }

    /**
     * Gets the attribute value for TypeApproval, using the alias name TypeApproval.
     * @return the value of TypeApproval
     */
    public String getTypeApproval() {
        return (String) getAttributeInternal(TYPEAPPROVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeApproval.
     * @param value value to set the TypeApproval
     */
    public void setTypeApproval(String value) {
        setAttributeInternal(TYPEAPPROVAL, value);
    }

    /**
     * Gets the attribute value for TmpItemid, using the alias name TmpItemid.
     * @return the value of TmpItemid
     */
    public String getTmpItemid() {
        return (String) getAttributeInternal(TMPITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TmpItemid.
     * @param value value to set the TmpItemid
     */
    public void setTmpItemid(String value) {
        setAttributeInternal(TMPITEMID, value);
    }

    /**
     * Gets the attribute value for TmpItemDesc, using the alias name TmpItemDesc.
     * @return the value of TmpItemDesc
     */
    public String getTmpItemDesc() {
        return (String) getAttributeInternal(TMPITEMDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TmpItemDesc.
     * @param value value to set the TmpItemDesc
     */
    public void setTmpItemDesc(String value) {
        setAttributeInternal(TMPITEMDESC, value);
    }

    /**
     * Gets the attribute value for Newmodle, using the alias name Newmodle.
     * @return the value of Newmodle
     */
    public String getNewmodle() {
        return (String) getAttributeInternal(NEWMODLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Newmodle.
     * @param value value to set the Newmodle
     */
    public void setNewmodle(String value) {
        setAttributeInternal(NEWMODLE, value);
    }

    /**
     * Gets the attribute value for Desce, using the alias name Desce.
     * @return the value of Desce
     */
    public String getDesce() {
        return (String) getAttributeInternal(DESCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Desce.
     * @param value value to set the Desce
     */
    public void setDesce(String value) {
        setAttributeInternal(DESCE, value);
    }

    /**
     * Gets the attribute value for Incentive, using the alias name Incentive.
     * @return the value of Incentive
     */
    public BigDecimal getIncentive() {
        return (BigDecimal) getAttributeInternal(INCENTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Incentive.
     * @param value value to set the Incentive
     */
    public void setIncentive(BigDecimal value) {
        setAttributeInternal(INCENTIVE, value);
    }

    /**
     * Gets the attribute value for IncMsg, using the alias name IncMsg.
     * @return the value of IncMsg
     */
    public String getIncMsg() {
        return (String) getAttributeInternal(INCMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncMsg.
     * @param value value to set the IncMsg
     */
    public void setIncMsg(String value) {
        setAttributeInternal(INCMSG, value);
    }

    /**
     * Gets the attribute value for SaleDays, using the alias name SaleDays.
     * @return the value of SaleDays
     */
    public BigDecimal getSaleDays() {
        return (BigDecimal) getAttributeInternal(SALEDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleDays.
     * @param value value to set the SaleDays
     */
    public void setSaleDays(BigDecimal value) {
        setAttributeInternal(SALEDAYS, value);
    }

    /**
     * Gets the attribute value for RetQtyExempted, using the alias name RetQtyExempted.
     * @return the value of RetQtyExempted
     */
    public String getRetQtyExempted() {
        return (String) getAttributeInternal(RETQTYEXEMPTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for RetQtyExempted.
     * @param value value to set the RetQtyExempted
     */
    public void setRetQtyExempted(String value) {
        setAttributeInternal(RETQTYEXEMPTED, value);
    }

    /**
     * Gets the attribute value for ItemRebateAct, using the alias name ItemRebateAct.
     * @return the value of ItemRebateAct
     */
    public String getItemRebateAct() {
        return (String) getAttributeInternal(ITEMREBATEACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemRebateAct.
     * @param value value to set the ItemRebateAct
     */
    public void setItemRebateAct(String value) {
        setAttributeInternal(ITEMREBATEACT, value);
    }

    /**
     * Gets the attribute value for RestrictBoxNo, using the alias name RestrictBoxNo.
     * @return the value of RestrictBoxNo
     */
    public String getRestrictBoxNo() {
        return (String) getAttributeInternal(RESTRICTBOXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RestrictBoxNo.
     * @param value value to set the RestrictBoxNo
     */
    public void setRestrictBoxNo(String value) {
        setAttributeInternal(RESTRICTBOXNO, value);
    }

    /**
     * Gets the attribute value for IsSpecial, using the alias name IsSpecial.
     * @return the value of IsSpecial
     */
    public String getIsSpecial() {
        return (String) getAttributeInternal(ISSPECIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSpecial.
     * @param value value to set the IsSpecial
     */
    public void setIsSpecial(String value) {
        setAttributeInternal(ISSPECIAL, value);
    }

    /**
     * Gets the attribute value for IsRunning, using the alias name IsRunning.
     * @return the value of IsRunning
     */
    public String getIsRunning() {
        return (String) getAttributeInternal(ISRUNNING);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsRunning.
     * @param value value to set the IsRunning
     */
    public void setIsRunning(String value) {
        setAttributeInternal(ISRUNNING, value);
    }

    /**
     * Gets the attribute value for CounterDeadDays, using the alias name CounterDeadDays.
     * @return the value of CounterDeadDays
     */
    public BigDecimal getCounterDeadDays() {
        return (BigDecimal) getAttributeInternal(COUNTERDEADDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CounterDeadDays.
     * @param value value to set the CounterDeadDays
     */
    public void setCounterDeadDays(BigDecimal value) {
        setAttributeInternal(COUNTERDEADDAYS, value);
    }

    /**
     * Gets the attribute value for RestrictRebateSo, using the alias name RestrictRebateSo.
     * @return the value of RestrictRebateSo
     */
    public String getRestrictRebateSo() {
        return (String) getAttributeInternal(RESTRICTREBATESO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RestrictRebateSo.
     * @param value value to set the RestrictRebateSo
     */
    public void setRestrictRebateSo(String value) {
        setAttributeInternal(RESTRICTREBATESO, value);
    }

    /**
     * Gets the attribute value for StopCustomer, using the alias name StopCustomer.
     * @return the value of StopCustomer
     */
    public String getStopCustomer() {
        return (String) getAttributeInternal(STOPCUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StopCustomer.
     * @param value value to set the StopCustomer
     */
    public void setStopCustomer(String value) {
        setAttributeInternal(STOPCUSTOMER, value);
    }

    /**
     * Gets the attribute value for ExcludeGiftQty, using the alias name ExcludeGiftQty.
     * @return the value of ExcludeGiftQty
     */
    public String getExcludeGiftQty() {
        return (String) getAttributeInternal(EXCLUDEGIFTQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExcludeGiftQty.
     * @param value value to set the ExcludeGiftQty
     */
    public void setExcludeGiftQty(String value) {
        setAttributeInternal(EXCLUDEGIFTQTY, value);
    }

    /**
     * Gets the attribute value for ImeiSerial, using the alias name ImeiSerial.
     * @return the value of ImeiSerial
     */
    public String getImeiSerial() {
        return (String) getAttributeInternal(IMEISERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImeiSerial.
     * @param value value to set the ImeiSerial
     */
    public void setImeiSerial(String value) {
        setAttributeInternal(IMEISERIAL, value);
    }

    /**
     * Gets the attribute value for ForceAllowReturn, using the alias name ForceAllowReturn.
     * @return the value of ForceAllowReturn
     */
    public String getForceAllowReturn() {
        return (String) getAttributeInternal(FORCEALLOWRETURN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ForceAllowReturn.
     * @param value value to set the ForceAllowReturn
     */
    public void setForceAllowReturn(String value) {
        setAttributeInternal(FORCEALLOWRETURN, value);
    }

    /**
     * Gets the attribute value for IsPreviousSameRate, using the alias name IsPreviousSameRate.
     * @return the value of IsPreviousSameRate
     */
    public String getIsPreviousSameRate() {
        return (String) getAttributeInternal(ISPREVIOUSSAMERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsPreviousSameRate.
     * @param value value to set the IsPreviousSameRate
     */
    public void setIsPreviousSameRate(String value) {
        setAttributeInternal(ISPREVIOUSSAMERATE, value);
    }

    /**
     * Gets the attribute value for PreviousRebateRate, using the alias name PreviousRebateRate.
     * @return the value of PreviousRebateRate
     */
    public BigDecimal getPreviousRebateRate() {
        return (BigDecimal) getAttributeInternal(PREVIOUSREBATERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousRebateRate.
     * @param value value to set the PreviousRebateRate
     */
    public void setPreviousRebateRate(BigDecimal value) {
        setAttributeInternal(PREVIOUSREBATERATE, value);
    }

    /**
     * Gets the attribute value for WrefreshDate, using the alias name WrefreshDate.
     * @return the value of WrefreshDate
     */
    public Date getWrefreshDate() {
        return (Date) getAttributeInternal(WREFRESHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WrefreshDate.
     * @param value value to set the WrefreshDate
     */
    public void setWrefreshDate(Date value) {
        setAttributeInternal(WREFRESHDATE, value);
    }

    /**
     * Gets the attribute value for IsStopWrefReturn, using the alias name IsStopWrefReturn.
     * @return the value of IsStopWrefReturn
     */
    public String getIsStopWrefReturn() {
        return (String) getAttributeInternal(ISSTOPWREFRETURN);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsStopWrefReturn.
     * @param value value to set the IsStopWrefReturn
     */
    public void setIsStopWrefReturn(String value) {
        setAttributeInternal(ISSTOPWREFRETURN, value);
    }

    /**
     * Gets the attribute value for RebateDays, using the alias name RebateDays.
     * @return the value of RebateDays
     */
    public Integer getRebateDays() {
        return (Integer) getAttributeInternal(REBATEDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for RebateDays.
     * @param value value to set the RebateDays
     */
    public void setRebateDays(Integer value) {
        setAttributeInternal(REBATEDAYS, value);
    }

    /**
     * Gets the attribute value for IncPst, using the alias name IncPst.
     * @return the value of IncPst
     */
    public BigDecimal getIncPst() {
        return (BigDecimal) getAttributeInternal(INCPST);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncPst.
     * @param value value to set the IncPst
     */
    public void setIncPst(BigDecimal value) {
        setAttributeInternal(INCPST, value);
    }

    /**
     * Gets the attribute value for EbsItemid, using the alias name EbsItemid.
     * @return the value of EbsItemid
     */
    public String getEbsItemid() {
        return (String) getAttributeInternal(EBSITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsItemid.
     * @param value value to set the EbsItemid
     */
    public void setEbsItemid(String value) {
        setAttributeInternal(EBSITEMID, value);
    }

    /**
     * Gets the attribute value for IsReturnAllow, using the alias name IsReturnAllow.
     * @return the value of IsReturnAllow
     */
    public String getIsReturnAllow() {
        return (String) getAttributeInternal(ISRETURNALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsReturnAllow.
     * @param value value to set the IsReturnAllow
     */
    public void setIsReturnAllow(String value) {
        setAttributeInternal(ISRETURNALLOW, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the value of Active
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for IsImeiWiseRetAllow, using the alias name IsImeiWiseRetAllow.
     * @return the value of IsImeiWiseRetAllow
     */
    public String getIsImeiWiseRetAllow() {
        return (String) getAttributeInternal(ISIMEIWISERETALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsImeiWiseRetAllow.
     * @param value value to set the IsImeiWiseRetAllow
     */
    public void setIsImeiWiseRetAllow(String value) {
        setAttributeInternal(ISIMEIWISERETALLOW, value);
    }

    /**
     * Gets the attribute value for ProdItemid, using the alias name ProdItemid.
     * @return the value of ProdItemid
     */
    public String getProdItemid() {
        return (String) getAttributeInternal(PRODITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdItemid.
     * @param value value to set the ProdItemid
     */
    public void setProdItemid(String value) {
        setAttributeInternal(PRODITEMID, value);
    }

    /**
     * Gets the attribute value for ScreenSize, using the alias name ScreenSize.
     * @return the value of ScreenSize
     */
    public BigDecimal getScreenSize() {
        return (BigDecimal) getAttributeInternal(SCREENSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ScreenSize.
     * @param value value to set the ScreenSize
     */
    public void setScreenSize(BigDecimal value) {
        setAttributeInternal(SCREENSIZE, value);
    }

    /**
     * Gets the attribute value for ActualFlatRate, using the alias name ActualFlatRate.
     * @return the value of ActualFlatRate
     */
    public String getActualFlatRate() {
        return (String) getAttributeInternal(ACTUALFLATRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActualFlatRate.
     * @param value value to set the ActualFlatRate
     */
    public void setActualFlatRate(String value) {
        setAttributeInternal(ACTUALFLATRATE, value);
    }

    /**
     * Gets the attribute value for IntraCompanyItemid, using the alias name IntraCompanyItemid.
     * @return the value of IntraCompanyItemid
     */
    public String getIntraCompanyItemid() {
        return (String) getAttributeInternal(INTRACOMPANYITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntraCompanyItemid.
     * @param value value to set the IntraCompanyItemid
     */
    public void setIntraCompanyItemid(String value) {
        setAttributeInternal(INTRACOMPANYITEMID, value);
    }

    /**
     * Gets the attribute value for IntraCompanyProductid, using the alias name IntraCompanyProductid.
     * @return the value of IntraCompanyProductid
     */
    public String getIntraCompanyProductid() {
        return (String) getAttributeInternal(INTRACOMPANYPRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IntraCompanyProductid.
     * @param value value to set the IntraCompanyProductid
     */
    public void setIntraCompanyProductid(String value) {
        setAttributeInternal(INTRACOMPANYPRODUCTID, value);
    }

    /**
     * Gets the attribute value for LandedCost, using the alias name LandedCost.
     * @return the value of LandedCost
     */
    public BigDecimal getLandedCost() {
        return (BigDecimal) getAttributeInternal(LANDEDCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for LandedCost.
     * @param value value to set the LandedCost
     */
    public void setLandedCost(BigDecimal value) {
        setAttributeInternal(LANDEDCOST, value);
    }

    /**
     * Gets the attribute value for BarCode, using the alias name BarCode.
     * @return the value of BarCode
     */
    public String getBarCode() {
        return (String) getAttributeInternal(BARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BarCode.
     * @param value value to set the BarCode
     */
    public void setBarCode(String value) {
        setAttributeInternal(BARCODE, value);
    }

    /**
     * Gets the attribute value for Siclassidn, using the alias name Siclassidn.
     * @return the value of Siclassidn
     */
    public String getSiclassidn() {
        return (String) getAttributeInternal(SICLASSIDN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Siclassidn.
     * @param value value to set the Siclassidn
     */
    public void setSiclassidn(String value) {
        setAttributeInternal(SICLASSIDN, value);
    }

    /**
     * Gets the attribute value for Sigroupidn, using the alias name Sigroupidn.
     * @return the value of Sigroupidn
     */
    public String getSigroupidn() {
        return (String) getAttributeInternal(SIGROUPIDN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Sigroupidn.
     * @param value value to set the Sigroupidn
     */
    public void setSigroupidn(String value) {
        setAttributeInternal(SIGROUPIDN, value);
    }

    /**
     * Gets the attribute value for Itgroupidn, using the alias name Itgroupidn.
     * @return the value of Itgroupidn
     */
    public String getItgroupidn() {
        return (String) getAttributeInternal(ITGROUPIDN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itgroupidn.
     * @param value value to set the Itgroupidn
     */
    public void setItgroupidn(String value) {
        setAttributeInternal(ITGROUPIDN, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the value of Discount
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for ItemCost, using the alias name ItemCost.
     * @return the value of ItemCost
     */
    public BigDecimal getItemCost() {
        return (BigDecimal) getAttributeInternal(ITEMCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemCost.
     * @param value value to set the ItemCost
     */
    public void setItemCost(BigDecimal value) {
        setAttributeInternal(ITEMCOST, value);
    }

    /**
     * Gets the attribute value for WcpShortName, using the alias name WcpShortName.
     * @return the value of WcpShortName
     */
    public String getWcpShortName() {
        return (String) getAttributeInternal(WCPSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for WcpShortName.
     * @param value value to set the WcpShortName
     */
    public void setWcpShortName(String value) {
        setAttributeInternal(WCPSHORTNAME, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInReceivedItemsLines() {
        return (RowIterator) getAttributeInternal(INRECEIVEDITEMSLINES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInItemTransferNoteLines() {
        return (RowIterator) getAttributeInternal(INITEMTRANSFERNOTELINES);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSoProducts() {
        return (RowIterator) getAttributeInternal(SOPRODUCTS);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInStoreItems() {
        return (RowIterator) getAttributeInternal(INSTOREITEMS);
    }


    /**
     * @param itemid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String itemid) {
        return new Key(new Object[] { itemid });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPISGenertePK("NO");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
           String pkValue=" P_ITEM_REF_ID.ID_ITEM_REF_ID('"+getSigroupid()+"')";
           
           String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "in_items", null, null);
           populateAttributeAsChanged(ITEMREFID, result);
            pkValue=" lpad(to_number(nvl(max(itemid),0)) + 1,15,'0')";
            result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "in_items", null, null);
            populateAttributeAsChanged(ITEMID, result);
            setProductid(getItemRefId());
            setOldItemid(getModelNo());
            
        } 
        super.doDML(operation, e);
        if (operation==DML_DELETE) {
           getSoProducts().first().remove();
       }
        if (operation!=DML_DELETE) {
            Row r=null;
            
            if (operation==DML_INSERT) {
               r= getSoProducts().createRow();
            }
            else {
                r=getSoProducts().first();
            }
            
            r.setAttribute("Pbrandid", getBrandid());
           r.setAttribute("ProductShortName", getModelNo());
           r.setAttribute("Uomsid", getUomsid());
           r.setAttribute("Pgroupid", getSigroupid());
           r.setAttribute("Companyid", ERPSolGlobClassModel.doGetUserCompanyCode());
           r.setAttribute("Productsubtype", getProductsubtype());
           r.setAttribute("ModelNo", getModelNo());
           r.setAttribute("CompDescription", getDescription());
           r.setAttribute("InvoiceDescription", getDescription());
           r.setAttribute("ItemStatus", getItemStatus());
           r.setAttribute("Divid", getDivid());
           if (operation==DML_INSERT) {
                getSoProducts().insertRow(r);
            }
        }
    }
}

