package erpsolims.erpsolimsmodel.erpsolimseo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 10 12:25:15 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InReceivedItemsSnoImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Storeid,
        Rnoteno,
        Lineno,
        Shelfid,
        SerialNo,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        StatusFlag,
        RecvItemSeqno,
        Itemid,
        ItemRefId,
        ValidateFlag,
        Boxno,
        TempBoxNo,
        CompanyCode;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int RNOTENO = AttributesEnum.Rnoteno.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int SHELFID = AttributesEnum.Shelfid.index();
    public static final int SERIALNO = AttributesEnum.SerialNo.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STATUSFLAG = AttributesEnum.StatusFlag.index();
    public static final int RECVITEMSEQNO = AttributesEnum.RecvItemSeqno.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMREFID = AttributesEnum.ItemRefId.index();
    public static final int VALIDATEFLAG = AttributesEnum.ValidateFlag.index();
    public static final int BOXNO = AttributesEnum.Boxno.index();
    public static final int TEMPBOXNO = AttributesEnum.TempBoxNo.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InReceivedItemsSnoImpl() {
    }

    /**
     * Gets the attribute value for Storeid, using the alias name Storeid.
     * @return the value of Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Storeid.
     * @param value value to set the Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for Rnoteno, using the alias name Rnoteno.
     * @return the value of Rnoteno
     */
    public String getRnoteno() {
        return (String) getAttributeInternal(RNOTENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rnoteno.
     * @param value value to set the Rnoteno
     */
    public void setRnoteno(String value) {
        setAttributeInternal(RNOTENO, value);
    }

    /**
     * Gets the attribute value for Lineno, using the alias name Lineno.
     * @return the value of Lineno
     */
    public Integer getLineno() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lineno.
     * @param value value to set the Lineno
     */
    public void setLineno(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for Shelfid, using the alias name Shelfid.
     * @return the value of Shelfid
     */
    public String getShelfid() {
        return (String) getAttributeInternal(SHELFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Shelfid.
     * @param value value to set the Shelfid
     */
    public void setShelfid(String value) {
        setAttributeInternal(SHELFID, value);
    }

    /**
     * Gets the attribute value for SerialNo, using the alias name SerialNo.
     * @return the value of SerialNo
     */
    public String getSerialNo() {
        return (String) getAttributeInternal(SERIALNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SerialNo.
     * @param value value to set the SerialNo
     */
    public void setSerialNo(String value) {
        setAttributeInternal(SERIALNO, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Timestamp getModifiedDate() {
        return (Timestamp) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Timestamp value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for StatusFlag, using the alias name StatusFlag.
     * @return the value of StatusFlag
     */
    public String getStatusFlag() {
        return (String) getAttributeInternal(STATUSFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatusFlag.
     * @param value value to set the StatusFlag
     */
    public void setStatusFlag(String value) {
        setAttributeInternal(STATUSFLAG, value);
    }

    /**
     * Gets the attribute value for RecvItemSeqno, using the alias name RecvItemSeqno.
     * @return the value of RecvItemSeqno
     */
    public BigDecimal getRecvItemSeqno() {
        return (BigDecimal) getAttributeInternal(RECVITEMSEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecvItemSeqno.
     * @param value value to set the RecvItemSeqno
     */
    public void setRecvItemSeqno(BigDecimal value) {
        setAttributeInternal(RECVITEMSEQNO, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemRefId, using the alias name ItemRefId.
     * @return the value of ItemRefId
     */
    public String getItemRefId() {
        return (String) getAttributeInternal(ITEMREFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemRefId.
     * @param value value to set the ItemRefId
     */
    public void setItemRefId(String value) {
        setAttributeInternal(ITEMREFID, value);
    }

    /**
     * Gets the attribute value for ValidateFlag, using the alias name ValidateFlag.
     * @return the value of ValidateFlag
     */
    public String getValidateFlag() {
        return (String) getAttributeInternal(VALIDATEFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidateFlag.
     * @param value value to set the ValidateFlag
     */
    public void setValidateFlag(String value) {
        setAttributeInternal(VALIDATEFLAG, value);
    }

    /**
     * Gets the attribute value for Boxno, using the alias name Boxno.
     * @return the value of Boxno
     */
    public String getBoxno() {
        return (String) getAttributeInternal(BOXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Boxno.
     * @param value value to set the Boxno
     */
    public void setBoxno(String value) {
        setAttributeInternal(BOXNO, value);
    }

    /**
     * Gets the attribute value for TempBoxNo, using the alias name TempBoxNo.
     * @return the value of TempBoxNo
     */
    public String getTempBoxNo() {
        return (String) getAttributeInternal(TEMPBOXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TempBoxNo.
     * @param value value to set the TempBoxNo
     */
    public void setTempBoxNo(String value) {
        setAttributeInternal(TEMPBOXNO, value);
    }

    /**
     * Gets the attribute value for CompanyCode, using the alias name CompanyCode.
     * @return the value of CompanyCode
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyCode.
     * @param value value to set the CompanyCode
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }

    /**
     * @param storeid key constituent
     * @param rnoteno key constituent
     * @param lineno key constituent
     * @param shelfid key constituent
     * @param recvItemSeqno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String storeid, String rnoteno, Integer lineno, String shelfid,
                                       BigDecimal recvItemSeqno) {
        return new Key(new Object[] { storeid, rnoteno, lineno, shelfid, recvItemSeqno });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolims.erpsolimsmodel.erpsolimseo.InReceivedItemsSno");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

