package erpsolims.erpsolimsmodel.erpsolimsvo;

import erpsolims.erpsolimsmodel.erpsolimseo.InDocumentShipmentHeaderImpl;

import erpsolims.erpsolimsmodel.erpsolimsvo.common.InDocumentShipmentHeaderVORow;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 10 22:14:54 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InDocumentShipmentHeaderVORowImpl extends ViewRowImpl implements InDocumentShipmentHeaderVORow {

    public static final int ENTITY_INDOCUMENTSHIPMENTHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ShipmentHeaderSno,
        ShipmentHeaderId,
        Locationid,
        ShipmentDate,
        DepartureFrom,
        VehicleNo,
        DriverName,
        DriverContactNo,
        CreatedBy,
        CreatedDate,
        ModifiedBy,
        ModifiedDate,
        Storeid,
        Posted,
        txtStoreName,
        Remarks,
        InDocumentShipmentLinesVO,
        AllStoresView,
        AccAllLocationsView,
        AccAllStoresView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int SHIPMENTHEADERSNO = AttributesEnum.ShipmentHeaderSno.index();
    public static final int SHIPMENTHEADERID = AttributesEnum.ShipmentHeaderId.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SHIPMENTDATE = AttributesEnum.ShipmentDate.index();
    public static final int DEPARTUREFROM = AttributesEnum.DepartureFrom.index();
    public static final int VEHICLENO = AttributesEnum.VehicleNo.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVERCONTACTNO = AttributesEnum.DriverContactNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int INDOCUMENTSHIPMENTLINESVO = AttributesEnum.InDocumentShipmentLinesVO.index();
    public static final int ALLSTORESVIEW = AttributesEnum.AllStoresView.index();
    public static final int ACCALLLOCATIONSVIEW = AttributesEnum.AccAllLocationsView.index();
    public static final int ACCALLSTORESVIEW = AttributesEnum.AccAllStoresView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InDocumentShipmentHeaderVORowImpl() {
    }

    /**
     * Gets InDocumentShipmentHeader entity object.
     * @return the InDocumentShipmentHeader
     */
    public InDocumentShipmentHeaderImpl getInDocumentShipmentHeader() {
        return (InDocumentShipmentHeaderImpl) getEntity(ENTITY_INDOCUMENTSHIPMENTHEADER);
    }

    /**
     * Gets the attribute value for SHIPMENT_HEADER_SNO using the alias name ShipmentHeaderSno.
     * @return the SHIPMENT_HEADER_SNO
     */
    public Integer getShipmentHeaderSno() {
        return (Integer) getAttributeInternal(SHIPMENTHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_HEADER_SNO using the alias name ShipmentHeaderSno.
     * @param value value to set the SHIPMENT_HEADER_SNO
     */
    public void setShipmentHeaderSno(Integer value) {
        setAttributeInternal(SHIPMENTHEADERSNO, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_HEADER_ID using the alias name ShipmentHeaderId.
     * @return the SHIPMENT_HEADER_ID
     */
    public String getShipmentHeaderId() {
        return (String) getAttributeInternal(SHIPMENTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_HEADER_ID using the alias name ShipmentHeaderId.
     * @param value value to set the SHIPMENT_HEADER_ID
     */
    public void setShipmentHeaderId(String value) {
        setAttributeInternal(SHIPMENTHEADERID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @return the SHIPMENT_DATE
     */
    public Date getShipmentDate() {
        return (Date) getAttributeInternal(SHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_DATE using the alias name ShipmentDate.
     * @param value value to set the SHIPMENT_DATE
     */
    public void setShipmentDate(Date value) {
        setAttributeInternal(SHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for DEPARTURE_FROM using the alias name DepartureFrom.
     * @return the DEPARTURE_FROM
     */
    public String getDepartureFrom() {
        return (String) getAttributeInternal(DEPARTUREFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTURE_FROM using the alias name DepartureFrom.
     * @param value value to set the DEPARTURE_FROM
     */
    public void setDepartureFrom(String value) {
        setAttributeInternal(DEPARTUREFROM, value);
    }

    /**
     * Gets the attribute value for VEHICLE_NO using the alias name VehicleNo.
     * @return the VEHICLE_NO
     */
    public String getVehicleNo() {
        return (String) getAttributeInternal(VEHICLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_NO using the alias name VehicleNo.
     * @param value value to set the VEHICLE_NO
     */
    public void setVehicleNo(String value) {
        setAttributeInternal(VEHICLENO, value);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_NAME using the alias name DriverName.
     * @param value value to set the DRIVER_NAME
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for DRIVER_CONTACT_NO using the alias name DriverContactNo.
     * @return the DRIVER_CONTACT_NO
     */
    public String getDriverContactNo() {
        return (String) getAttributeInternal(DRIVERCONTACTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_CONTACT_NO using the alias name DriverContactNo.
     * @param value value to set the DRIVER_CONTACT_NO
     */
    public void setDriverContactNo(String value) {
        setAttributeInternal(DRIVERCONTACTNO, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InDocumentShipmentLinesVO.
     */
    public RowIterator getInDocumentShipmentLinesVO() {
        return (RowIterator) getAttributeInternal(INDOCUMENTSHIPMENTLINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresView.
     */
    public Row getAllStoresView() {
        return (Row) getAttributeInternal(ALLSTORESVIEW);
    }

    /**
     * Sets the master-detail link AllStoresView between this object and <code>value</code>.
     */
    public void setAllStoresView(Row value) {
        setAttributeInternal(ALLSTORESVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsView.
     */
    public RowSet getAccAllLocationsView() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresView.
     */
    public RowSet getAccAllStoresView() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVIEW);
    }
    public void doSuperviseShipment() {
        setPosted("Y");
        getDBTransaction().commit();
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

