package erpsolims.erpsolimsmodel.erpsolimsvo;

import erpsolims.erpsolimsmodel.erpsolimseo.InItemTransferNoteImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 23 16:01:08 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InItemTransferNoteViewRowImpl extends ViewRowImpl {


    public static final int ENTITY_INITEMTRANSFERNOTE = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Sendingstoreid,
        Stnno,
        DateOfTransfer,
        Receivingstoreid,
        TransferReference,
        SourceDocRef,
        Remarks,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Posted,
        PostedBy,
        Companyid,
        Deptid,
        Locationid,
        Transfertype,
        Gatepassrefno,
        Gatepassdate,
        Transportno,
        Bankrefno,
        TransporterName,
        BiltyNo,
        BiltyDate,
        IgpNo,
        AssociateLocationid,
        BillOfEntry,
        IsMigrated,
        MigratedDate,
        Stnnoseq,
        txtStoreName,
        txtLocationName,
        txtReceivingSroreName,
        Supplierid,
        InItemTransferNoteLinesView,
        AllStoresView,
        AllLocationsView,
        AllStoresView1,
        AccAllStoresView,
        AccAllLocationsView,
        AccVWYesNoQVO,
        AccPuSuppliersView,
        AccAllStoresReceivingView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SENDINGSTOREID = AttributesEnum.Sendingstoreid.index();
    public static final int STNNO = AttributesEnum.Stnno.index();
    public static final int DATEOFTRANSFER = AttributesEnum.DateOfTransfer.index();
    public static final int RECEIVINGSTOREID = AttributesEnum.Receivingstoreid.index();
    public static final int TRANSFERREFERENCE = AttributesEnum.TransferReference.index();
    public static final int SOURCEDOCREF = AttributesEnum.SourceDocRef.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.PostedBy.index();
    public static final int COMPANYID = AttributesEnum.Companyid.index();
    public static final int DEPTID = AttributesEnum.Deptid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int TRANSFERTYPE = AttributesEnum.Transfertype.index();
    public static final int GATEPASSREFNO = AttributesEnum.Gatepassrefno.index();
    public static final int GATEPASSDATE = AttributesEnum.Gatepassdate.index();
    public static final int TRANSPORTNO = AttributesEnum.Transportno.index();
    public static final int BANKREFNO = AttributesEnum.Bankrefno.index();
    public static final int TRANSPORTERNAME = AttributesEnum.TransporterName.index();
    public static final int BILTYNO = AttributesEnum.BiltyNo.index();
    public static final int BILTYDATE = AttributesEnum.BiltyDate.index();
    public static final int IGPNO = AttributesEnum.IgpNo.index();
    public static final int ASSOCIATELOCATIONID = AttributesEnum.AssociateLocationid.index();
    public static final int BILLOFENTRY = AttributesEnum.BillOfEntry.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int STNNOSEQ = AttributesEnum.Stnnoseq.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTRECEIVINGSRORENAME = AttributesEnum.txtReceivingSroreName.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int INITEMTRANSFERNOTELINESVIEW = AttributesEnum.InItemTransferNoteLinesView.index();
    public static final int ALLSTORESVIEW = AttributesEnum.AllStoresView.index();
    public static final int ALLLOCATIONSVIEW = AttributesEnum.AllLocationsView.index();
    public static final int ALLSTORESVIEW1 = AttributesEnum.AllStoresView1.index();
    public static final int ACCALLSTORESVIEW = AttributesEnum.AccAllStoresView.index();
    public static final int ACCALLLOCATIONSVIEW = AttributesEnum.AccAllLocationsView.index();
    public static final int ACCVWYESNOQVO = AttributesEnum.AccVWYesNoQVO.index();
    public static final int ACCPUSUPPLIERSVIEW = AttributesEnum.AccPuSuppliersView.index();
    public static final int ACCALLSTORESRECEIVINGVIEW = AttributesEnum.AccAllStoresReceivingView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InItemTransferNoteViewRowImpl() {
    }

    /**
     * Gets InItemTransferNote entity object.
     * @return the InItemTransferNote
     */
    public InItemTransferNoteImpl getInItemTransferNote() {
        return (InItemTransferNoteImpl) getEntity(ENTITY_INITEMTRANSFERNOTE);
    }

    /**
     * Gets the attribute value for SENDINGSTOREID using the alias name Sendingstoreid.
     * @return the SENDINGSTOREID
     */
    public String getSendingstoreid() {
        return (String) getAttributeInternal(SENDINGSTOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for SENDINGSTOREID using the alias name Sendingstoreid.
     * @param value value to set the SENDINGSTOREID
     */
    public void setSendingstoreid(String value) {
        setAttributeInternal(SENDINGSTOREID, value);
    }

    /**
     * Gets the attribute value for STNNO using the alias name Stnno.
     * @return the STNNO
     */
    public String getStnno() {
        return (String) getAttributeInternal(STNNO);
    }

    /**
     * Sets <code>value</code> as attribute value for STNNO using the alias name Stnno.
     * @param value value to set the STNNO
     */
    public void setStnno(String value) {
        setAttributeInternal(STNNO, value);
    }

    /**
     * Gets the attribute value for DATE_OF_TRANSFER using the alias name DateOfTransfer.
     * @return the DATE_OF_TRANSFER
     */
    public Date getDateOfTransfer() {
        return (Date) getAttributeInternal(DATEOFTRANSFER);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_OF_TRANSFER using the alias name DateOfTransfer.
     * @param value value to set the DATE_OF_TRANSFER
     */
    public void setDateOfTransfer(Date value) {
        setAttributeInternal(DATEOFTRANSFER, value);
    }

    /**
     * Gets the attribute value for RECEIVINGSTOREID using the alias name Receivingstoreid.
     * @return the RECEIVINGSTOREID
     */
    public String getReceivingstoreid() {
        return (String) getAttributeInternal(RECEIVINGSTOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVINGSTOREID using the alias name Receivingstoreid.
     * @param value value to set the RECEIVINGSTOREID
     */
    public void setReceivingstoreid(String value) {
        setAttributeInternal(RECEIVINGSTOREID, value);
    }

    /**
     * Gets the attribute value for TRANSFER_REFERENCE using the alias name TransferReference.
     * @return the TRANSFER_REFERENCE
     */
    public String getTransferReference() {
        return (String) getAttributeInternal(TRANSFERREFERENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFER_REFERENCE using the alias name TransferReference.
     * @param value value to set the TRANSFER_REFERENCE
     */
    public void setTransferReference(String value) {
        setAttributeInternal(TRANSFERREFERENCE, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOC_REF using the alias name SourceDocRef.
     * @return the SOURCE_DOC_REF
     */
    public String getSourceDocRef() {
        return (String) getAttributeInternal(SOURCEDOCREF);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOC_REF using the alias name SourceDocRef.
     * @param value value to set the SOURCE_DOC_REF
     */
    public void setSourceDocRef(String value) {
        setAttributeInternal(SOURCEDOCREF, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTED_BY using the alias name PostedBy.
     * @return the POSTED_BY
     */
    public String getPostedBy() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED_BY using the alias name PostedBy.
     * @param value value to set the POSTED_BY
     */
    public void setPostedBy(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for COMPANYID using the alias name Companyid.
     * @return the COMPANYID
     */
    public String getCompanyid() {
        return (String) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANYID using the alias name Companyid.
     * @param value value to set the COMPANYID
     */
    public void setCompanyid(String value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for DEPTID using the alias name Deptid.
     * @return the DEPTID
     */
    public String getDeptid() {
        return (String) getAttributeInternal(DEPTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPTID using the alias name Deptid.
     * @param value value to set the DEPTID
     */
    public void setDeptid(String value) {
        setAttributeInternal(DEPTID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for TRANSFERTYPE using the alias name Transfertype.
     * @return the TRANSFERTYPE
     */
    public String getTransfertype() {
        return (String) getAttributeInternal(TRANSFERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSFERTYPE using the alias name Transfertype.
     * @param value value to set the TRANSFERTYPE
     */
    public void setTransfertype(String value) {
        setAttributeInternal(TRANSFERTYPE, value);
    }

    /**
     * Gets the attribute value for GATEPASSREFNO using the alias name Gatepassrefno.
     * @return the GATEPASSREFNO
     */
    public String getGatepassrefno() {
        return (String) getAttributeInternal(GATEPASSREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GATEPASSREFNO using the alias name Gatepassrefno.
     * @param value value to set the GATEPASSREFNO
     */
    public void setGatepassrefno(String value) {
        setAttributeInternal(GATEPASSREFNO, value);
    }

    /**
     * Gets the attribute value for GATEPASSDATE using the alias name Gatepassdate.
     * @return the GATEPASSDATE
     */
    public Date getGatepassdate() {
        return (Date) getAttributeInternal(GATEPASSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GATEPASSDATE using the alias name Gatepassdate.
     * @param value value to set the GATEPASSDATE
     */
    public void setGatepassdate(Date value) {
        setAttributeInternal(GATEPASSDATE, value);
    }

    /**
     * Gets the attribute value for TRANSPORTNO using the alias name Transportno.
     * @return the TRANSPORTNO
     */
    public String getTransportno() {
        return (String) getAttributeInternal(TRANSPORTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORTNO using the alias name Transportno.
     * @param value value to set the TRANSPORTNO
     */
    public void setTransportno(String value) {
        setAttributeInternal(TRANSPORTNO, value);
    }

    /**
     * Gets the attribute value for BANKREFNO using the alias name Bankrefno.
     * @return the BANKREFNO
     */
    public String getBankrefno() {
        return (String) getAttributeInternal(BANKREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BANKREFNO using the alias name Bankrefno.
     * @param value value to set the BANKREFNO
     */
    public void setBankrefno(String value) {
        setAttributeInternal(BANKREFNO, value);
    }

    /**
     * Gets the attribute value for TRANSPORTER_NAME using the alias name TransporterName.
     * @return the TRANSPORTER_NAME
     */
    public String getTransporterName() {
        return (String) getAttributeInternal(TRANSPORTERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSPORTER_NAME using the alias name TransporterName.
     * @param value value to set the TRANSPORTER_NAME
     */
    public void setTransporterName(String value) {
        setAttributeInternal(TRANSPORTERNAME, value);
    }

    /**
     * Gets the attribute value for BILTY_NO using the alias name BiltyNo.
     * @return the BILTY_NO
     */
    public String getBiltyNo() {
        return (String) getAttributeInternal(BILTYNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BILTY_NO using the alias name BiltyNo.
     * @param value value to set the BILTY_NO
     */
    public void setBiltyNo(String value) {
        setAttributeInternal(BILTYNO, value);
    }

    /**
     * Gets the attribute value for BILTY_DATE using the alias name BiltyDate.
     * @return the BILTY_DATE
     */
    public Date getBiltyDate() {
        return (Date) getAttributeInternal(BILTYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BILTY_DATE using the alias name BiltyDate.
     * @param value value to set the BILTY_DATE
     */
    public void setBiltyDate(Date value) {
        setAttributeInternal(BILTYDATE, value);
    }

    /**
     * Gets the attribute value for IGP_NO using the alias name IgpNo.
     * @return the IGP_NO
     */
    public String getIgpNo() {
        return (String) getAttributeInternal(IGPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for IGP_NO using the alias name IgpNo.
     * @param value value to set the IGP_NO
     */
    public void setIgpNo(String value) {
        setAttributeInternal(IGPNO, value);
    }

    /**
     * Gets the attribute value for ASSOCIATE_LOCATIONID using the alias name AssociateLocationid.
     * @return the ASSOCIATE_LOCATIONID
     */
    public String getAssociateLocationid() {
        return (String) getAttributeInternal(ASSOCIATELOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSOCIATE_LOCATIONID using the alias name AssociateLocationid.
     * @param value value to set the ASSOCIATE_LOCATIONID
     */
    public void setAssociateLocationid(String value) {
        setAttributeInternal(ASSOCIATELOCATIONID, value);
    }

    /**
     * Gets the attribute value for BILL_OF_ENTRY using the alias name BillOfEntry.
     * @return the BILL_OF_ENTRY
     */
    public String getBillOfEntry() {
        return (String) getAttributeInternal(BILLOFENTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for BILL_OF_ENTRY using the alias name BillOfEntry.
     * @param value value to set the BILL_OF_ENTRY
     */
    public void setBillOfEntry(String value) {
        setAttributeInternal(BILLOFENTRY, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for STNNOSEQ using the alias name Stnnoseq.
     * @return the STNNOSEQ
     */
    public Integer getStnnoseq() {
        return (Integer) getAttributeInternal(STNNOSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for STNNOSEQ using the alias name Stnnoseq.
     * @param value value to set the STNNOSEQ
     */
    public void setStnnoseq(Integer value) {
        setAttributeInternal(STNNOSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_RECEIVING_SRORE_NAME using the alias name txtReceivingSroreName.
     * @return the TXT_RECEIVING_SRORE_NAME
     */
    public String gettxtReceivingSroreName() {
        return (String) getAttributeInternal(TXTRECEIVINGSRORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_RECEIVING_SRORE_NAME using the alias name txtReceivingSroreName.
     * @param value value to set the TXT_RECEIVING_SRORE_NAME
     */
    public void settxtReceivingSroreName(String value) {
        setAttributeInternal(TXTRECEIVINGSRORENAME, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InItemTransferNoteLinesView.
     */
    public RowIterator getInItemTransferNoteLinesView() {
        return (RowIterator) getAttributeInternal(INITEMTRANSFERNOTELINESVIEW);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresView.
     */
    public Row getAllStoresView() {
        return (Row) getAttributeInternal(ALLSTORESVIEW);
    }

    /**
     * Sets the master-detail link AllStoresView between this object and <code>value</code>.
     */
    public void setAllStoresView(Row value) {
        setAttributeInternal(ALLSTORESVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllLocationsView.
     */
    public Row getAllLocationsView() {
        return (Row) getAttributeInternal(ALLLOCATIONSVIEW);
    }

    /**
     * Sets the master-detail link AllLocationsView between this object and <code>value</code>.
     */
    public void setAllLocationsView(Row value) {
        setAttributeInternal(ALLLOCATIONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresView1.
     */
    public Row getAllStoresView1() {
        return (Row) getAttributeInternal(ALLSTORESVIEW1);
    }

    /**
     * Sets the master-detail link AllStoresView1 between this object and <code>value</code>.
     */
    public void setAllStoresView1(Row value) {
        setAttributeInternal(ALLSTORESVIEW1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresView.
     */
    public RowSet getAccAllStoresView() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsView.
     */
    public RowSet getAccAllLocationsView() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccVWYesNoQVO.
     */
    public RowSet getAccVWYesNoQVO() {
        return (RowSet) getAttributeInternal(ACCVWYESNOQVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPuSuppliersView.
     */
    public RowSet getAccPuSuppliersView() {
        return (RowSet) getAttributeInternal(ACCPUSUPPLIERSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresReceivingView.
     */
    public RowSet getAccAllStoresReceivingView() {
        return (RowSet) getAttributeInternal(ACCALLSTORESRECEIVINGVIEW);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

