package erpsolims.erpsolimsmodel.erpsolimsvo;

import erpsolims.erpsolimsmodel.erpsolimsvo.common.InItemTransferNoteImeiView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 25 18:00:54 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InItemTransferNoteImeiViewImpl extends ViewObjectImpl implements InItemTransferNoteImeiView {
    /**
     * This is the default constructor (do not remove).
     */
    public InItemTransferNoteImeiViewImpl() {
    }

    /**
     * Returns the variable value for P_ADF_STNLINESEQ.
     * @return variable value for P_ADF_STNLINESEQ
     */
    public Integer getP_ADF_STNLINESEQ() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_STNLINESEQ");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_STNLINESEQ.
     * @param value value to bind as P_ADF_STNLINESEQ
     */
    public void setP_ADF_STNLINESEQ(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_STNLINESEQ", value);
    }
    public void doERPSolRemoveSTNBox() {
        try {
            //if selected box is null then exception will be handled
            String ERPSolBox = this.getCurrentRow().getAttribute("TempBoxNo").toString();
            this.setRangeSize(-1);

            for (int i = 0; i < this.getViewObject().getEstimatedRowCount(); i++) {
                try {//if row box no is null then system will move to next record in loop
                    if (getRowAtRangeIndex(i).getAttribute("TempBoxNo").toString().equals(ERPSolBox)) {
                        getRowAtRangeIndex(i).remove();
                        i--;
                    }
                } catch (Exception e) {
                    // TODO: Add catch code
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            // TODO: Add catch code
    //            e.printStackTrace();
        }

    }
}

