package erpsolims.erpsolimsmodel.erpsolimsqvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 25 14:09:07 PKT 2021
// ---------------------------------------------------------------------
public interface VwInInventoryReportQVO extends ViewObject {
    void doSetInventoryReportDefaults();

    void doExecuteStockAgingProcedure();

    void doSetERPSolINDocumentUnsubmit();
}

