package erpsolims.erpsolimsmodel.erpsolimsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 25 18:02:05 PKT 2022
// ---------------------------------------------------------------------
public interface InItemTransferNoteImeiView extends ViewObject {
    void doERPSolRemoveSTNBox();
}

