package erpsolims.erpsolimsmodel.erpsolimsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 23 15:05:17 PKT 2022
// ---------------------------------------------------------------------
public interface InItemTransferNoteView extends ViewObject {
    void doSuperviseSTN();
}

