package erpsolims.erpsolimsmodel.erpsolimsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 17 14:27:44 PKT 2023
// ---------------------------------------------------------------------
public interface InReceivedItemsSnoView extends ViewObject {
    void doERPSolRemoveGRNBox();
}

