package erpsolims.erpsolimsmodel.erpsolimsvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Dec 11 15:08:40 PKT 2021
// ---------------------------------------------------------------------
public interface InReceivedItemsView extends ViewObject {
    void doSuperviseGRN();
}

